name: Grails Tests


on: push

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['11']
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache local .gradle
        uses: actions/cache@v2
        with:
          path: .gradle
          key: ${{ runner.os }}-dotgradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-dotgradle-

      - name: Cache home .gradle/wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - name: Cache home .gradle/caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Grails unit tests
        run: |
          ./gradlew --no-daemon test
          ./gradlew --no-daemon integrationTest
        continue-on-error: true

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
          fail_on_test_failures: true

